apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (bc7d9f4f)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (bc7d9f4f)
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: MYSQL_DB
              value: myDb
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PASSWORD
              value: admin
            - name: MYSQL_USER
              value: admin
          image: backend
          name: backend
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
